// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIIc4WgHFj4ED8d-laMRQffBC9JxnK3p8',
    appId: '1:118503040210:web:8fd6c26d7622a84854790b',
    messagingSenderId: '118503040210',
    projectId: 'ohkaraoapp-3258d',
    authDomain: 'ohkaraoapp-3258d.firebaseapp.com',
    storageBucket: 'ohkaraoapp-3258d.firebasestorage.app',
    measurementId: 'G-LZ6JCRG19K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-SJiARbwaAdwFUQP1JJqvBUn0hUDPXHA',
    appId: '1:118503040210:android:10deab2ddcc134aa54790b',
    messagingSenderId: '118503040210',
    projectId: 'ohkaraoapp-3258d',
    storageBucket: 'ohkaraoapp-3258d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO_Bdqg_6I4KJRVWEkurpAT4t4nlj6CPI',
    appId: '1:118503040210:ios:74eb4a6e055bdd0154790b',
    messagingSenderId: '118503040210',
    projectId: 'ohkaraoapp-3258d',
    storageBucket: 'ohkaraoapp-3258d.firebasestorage.app',
    iosBundleId: 'com.example.testUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO_Bdqg_6I4KJRVWEkurpAT4t4nlj6CPI',
    appId: '1:118503040210:ios:74eb4a6e055bdd0154790b',
    messagingSenderId: '118503040210',
    projectId: 'ohkaraoapp-3258d',
    storageBucket: 'ohkaraoapp-3258d.firebasestorage.app',
    iosBundleId: 'com.example.testUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIIc4WgHFj4ED8d-laMRQffBC9JxnK3p8',
    appId: '1:118503040210:web:dd1673b891d516cb54790b',
    messagingSenderId: '118503040210',
    projectId: 'ohkaraoapp-3258d',
    authDomain: 'ohkaraoapp-3258d.firebaseapp.com',
    storageBucket: 'ohkaraoapp-3258d.firebasestorage.app',
    measurementId: 'G-JZM60V93KR',
  );
}
